[package]
name = "zap_backend"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "zap_backend"
path = "src/lib.rs"

[dependencies]
snailquote = "0.3.1"

[dev-dependencies]
test_bin = "0.4.0"
